MyDiplom/Controllers/UserAccountController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDiplom.Models;
using System.Diagnostics;
using System.Security.Claims;

namespace MyDiplom.Controllers
{
    public class UserAccountController : Controller
    {
        private readonly ILogger<UserAccountController> _logger;
        private ChildrenContext db = new ChildrenContext();
        public int id_user;
        public User user;
        public UserAccountController(ILogger<UserAccountController> logger)
        {
            _logger = logger;
        }
      

        [HttpGet("UserAccount/Account/{id?}")] // Метод с параметром id
        public IActionResult Account(int id)
        {
            id_user = id;

            if (id == 0)
            {
                return BadRequest();
            }

            var user = db.Users.Include(u => u.Role).FirstOrDefault(e => e.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            int userId = GetAuthenticatedUserId(); // Получаем UserId текущего пользователя
            ViewBag.UserId = userId; // Передаем UserId в представление

            if (user.RoleId == 3)
            {
                var employeeData = db.Employees.FirstOrDefault(e => e.UserId == id);
                return View("Account_employee", employeeData);
            }
            else if (user.RoleId == 2)
            {
                var childrenData = user.Children; 
                return View("Account", user); 
            }
            else if (user.RoleId == 1)
            {
                  return View("Account_admin", user); 
            }
            return View("DefaultView");
            
        }
        private int GetAuthenticatedUserId()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                if (userIdClaim != null && int.TryParse(userIdClaim.Value, out int userId))
                {
                    return userId;
                }
            }
            return 0;
        }

        [HttpGet("UserAccount/Account_employee/{id?}")] // Метод с параметром id
        public IActionResult Account_employee(int id)
        {
            id_user = id;

            if (id == 0)
            {
                return BadRequest();
            }

            int userId = GetAuthenticatedUserId(); // Получаем UserId текущего пользователя
            ViewBag.UserId = userId; // Передаем UserId в представление
            var user = db.Users.Include(u => u.Role).FirstOrDefault(e => e.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
            var employeeData = db.Employees.FirstOrDefault(e => e.UserId == id);
            return View("Account_employee", employeeData);
            
           

        }

        [HttpGet("UserAccount/Account_admin/{id?}")] // Метод с параметром id
        public IActionResult Account_admin(int id)
        {
            id_user = id;

            if (id == 0)
            {
                return BadRequest();
            }

            int userId = GetAuthenticatedUserId(); // Получаем UserId текущего пользователя
            ViewBag.UserId = userId; // Передаем UserId в представление
            var user = db.Users.Include(u => u.Role).FirstOrDefault(e => e.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
           
            return View("Account_admin", user);



        }



        [HttpPost]
        public async Task<IActionResult> UploadPhoto(int userId, IFormFile photo)
        {
            if (photo == null || photo.Length == 0)
            {
                ModelState.AddModelError("Photo", "Выберите файл для загрузки.");
                return RedirectToAction("Account", new { id = userId });
            }

            var user = await db.Users.FindAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            // Сохраняем изображение в виде массива байтов
            user.Photo = await GetBytesFromFormFile(photo);

            await db.SaveChangesAsync();

            return RedirectToAction("Account", new { id = userId });
        }

        public IActionResult GetPhoto(int id)
        {
            var user = db.Users.Find(id);
            if (user?.Photo != null)
            {
                return File(user.Photo, "image/jpeg");
            }

            return NotFound();
        }

        private async Task<byte[]> GetBytesFromFormFile(IFormFile file)
        {
            using var memoryStream = new MemoryStream();
            await file.CopyToAsync(memoryStream);
            return memoryStream.ToArray();
        }

     
    }
}

MyDiplom/Views/UserAccount/Account.cshtml
@model User

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>Аккаунт пользователя</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {

            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
        }



        .profile-icon {
            width: 30px; /* Размер иконки профиля */
        }

        .content {
            margin: 20px auto;
            padding: 20px;
            background: rgba(255, 255, 255, 0.9);
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 800px;
        }

        .row {
            display: flex;
            gap: 20px;
        }

        .col-md-4, .col-md-8 {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .col-md-4 {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .col-md-8 {
            flex: 2;
        }

        .profile-image {
            width: 150px; /* Размер изображения профиля */
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            border: 3px solid #ff6f61; /* Обводка */
            margin-bottom: 20px;
        }

        .file-input-wrapper {
            position: relative;
            display: inline-block;
            margin-top: 10px;
        }

        .file-input {
            display: none;
        }



    </style>
</head>
<body>
    <nav style="width:1000px;">
        <a href="@Url.Action("Index", "Home",new {  id = ViewBag.UserId })" class="nav-icon-left">
            <img src="~/css/Main_Icon.png" alt="Profile Icon" class="profile-icon">
        </a>
        <div class="nav-links">
            <a href="@Url.Action("Index", "Home",new {  id = ViewBag.UserId })">Главная</a>
            <a href="@Url.Action("List_employee", "List")">Воспитатели</a>
            <a href="@Url.Action("List_Group", "List")">Группы</a>
            <a href="@Url.Action("Messenger", "Chat" )">Сообщения</a>
            <div class="animation"></div>
        </div>
            <a href="@Url.Action("Account", "UserAccount", new {  id = ViewBag.UserId })">
                <img src="~/css/my_acc.png" alt="Profile Icon" class="profile-icon">
            </a>
        <a href="@Url.Action("Main_no_auth", "Home")">
            <img src="~/css/out.png" alt="Profile Icon" class="profile-icon">
        </a>

    </nav>
    <div class="content">
        <div class="row">
            <div class="col-md-4">
                @if (Model.Photo != null)
                {
                    <img src="@Url.Action("GetPhoto", "UserAccount", new { id = Model.UserId })" class="profile-image" />
                }
                else
                {
                    <img src="~/css/ph3.jpg" class="profile-image" />
                }

                <form asp-action="UploadPhoto" asp-controller="UserAccount" method="post" enctype="multipart/form-data">
                    <div class="file-input-wrapper">
                        <label for="file-upload" class="btn file-label">Выберите файл</label>
                        <input id="file-upload" type="file" name="photo" accept="image/*" required class="file-input" />
                        <input type="hidden" name="userId" value="@Model.UserId" />
                        <button type="submit" class="btn">Загрузить фотографию</button>
                    </div>
                </form>
            </div>
            <div class="col-md-8">
                <h2>@Model.Username</h2>
                <label>Email: @Model.Email</label>
                <br/>
                <label>Телефон: @Model.Phone</label>
            </div>
        </div>
    </div>
</body>
</html>

MyDiplom/Views/UserAccount/Account_admin.cshtml
@model User

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>Аккаунт пользователя</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
           
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
        }

      

        .profile-icon {
            width: 30px; /* Размер иконки профиля */
        }

        .content {
            margin: 20px auto;
            padding: 20px;
            background: rgba(255, 255, 255, 0.9);
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 800px;
        }

        .row {
            display: flex;
            gap: 20px;
        }

        .col-md-4, .col-md-8 {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .col-md-4 {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .col-md-8 {
            flex: 2;
        }

        .profile-image {
            width: 150px; /* Размер изображения профиля */
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            border: 3px solid #ff6f61; /* Обводка */
            margin-bottom: 20px;
        }

        .file-input-wrapper {
            position: relative;
            display: inline-block;
            margin-top: 10px;
        }

        .file-input {
            display: none;
        }


    
    </style>
</head>
<body>
    <nav style="width:1000px;">
        <a href="@Url.Action("Main_admin", "Home")" class="nav-icon-left">
            <img src="~/css/Main_Icon.png" alt="Profile Icon" class="profile-icon">
        </a>
        <div class="nav-links">
            <a href="@Url.Action("Main_admin", "Home")">Главная</a>
            <a href="@Url.Action("List_employee_admin", "List")">Воспитатели</a>
            <a href="@Url.Action("List_Group_admin", "List")">Группы</a>
            <a href="@Url.Action("Register", "Home")">Регистрация</a>
            <div class="animation"></div>
        </div>
        <a href="@Url.Action("Account_admin", "UserAccount", new { id = ViewBag.UserId })">
            <img src="~/css/my_acc.png" alt="Profile Icon" class="profile-icon">
        </a>
        <a href="@Url.Action("Main_no_auth", "Home")">
            <img src="~/css/out.png" alt="Profile Icon" class="profile-icon">
        </a>

    </nav>
    <div class="content">
        <div class="row">
            <div class="col-md-4">
                @if (Model.Photo != null)
                {
                    <img src="@Url.Action("GetPhoto", "UserAccount", new { id = Model.UserId })" class="profile-image" />
                }
                else
                {
                    <img src="~/css/ph3.jpg" class="profile-image" />
                }

                <form asp-action="UploadPhoto" asp-controller="UserAccount" method="post" enctype="multipart/form-data">
                    <div class="file-input-wrapper">
                        <label for="file-upload" class="btn file-label">Выберите файл</label>
                        <input id="file-upload" type="file" name="photo" accept="image/*" required class="file-input" />
                        <input type="hidden" name="userId" value="@Model.UserId" />
                        <button type="submit" class="btn">Загрузить фотографию</button>
                    </div>
                </form>
            </div>
            <div class="col-md-8">
                <h2>@Model.Username</h2>
                <label>Email: @Model.Email</label>
                <br/>
                <label>Телефон: @Model.Phone</label>
            </div>
        </div>
    </div>
</body>
</html>

MyDiplom/Views/UserAccount/Account_employee.cshtml
@model Employee

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>Аккаунт пользователя</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
           
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
        }

      

        .profile-icon {
            width: 30px; /* Размер иконки профиля */
        }

        .content {
            margin: 20px auto;
            padding: 20px;
            background: rgba(255, 255, 255, 0.9);
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 800px;
        }

        .row {
            display: flex;
            gap: 20px;
        }

        .col-md-4, .col-md-8 {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .col-md-4 {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .col-md-8 {
            flex: 2;
        }

        .profile-image {
            width: 150px; /* Размер изображения профиля */
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            border: 3px solid #ff6f61; /* Обводка */
            margin-bottom: 20px;
        }

        .file-input-wrapper {
            position: relative;
            display: inline-block;
            margin-top: 10px;
        }

        .file-input {
            display: none;
        }


    
    </style>
</head>
<body>
    <nav style="width:1000px">
        <a href="@Url.Action("Main_employee", "Home")" class="nav-icon-left">
            <img src="~/css/Main_Icon.png" alt="Profile Icon" class="profile-icon">
        </a>
        <div class="nav-links">
            <a href="@Url.Action("Main_employee", "Home", new {  id = ViewBag.UserId })">Главная</a>
            <a href="@Url.Action("List_employee_emp", "List")">Воспитатели</a>
            <a href="@Url.Action("List_Group_employee", "List")">Расписание</a>
            <a href="@Url.Action("Messenger_emp", "Chat" )">Сообщения</a>
            <div class="animation"></div>
        </div>
        <a href="@Url.Action("Account_employee", "UserAccount", new {  id = ViewBag.UserId })">
            <img src="~/css/my_acc.png" alt="Profile Icon" class="profile-icon">
        </a>
        <a href="@Url.Action("Main_no_auth", "Home")">
            <img src="~/css/out.png" alt="Profile Icon" class="profile-icon">
        </a>
    </nav>
  
<div class="content">
    <div class="row">
        <div class="col-md-4">
            @if (Model.User.Photo != null)
            {
                <img src="@Url.Action("GetPhoto", "UserAccount", new { id = Model.UserId })" class="profile-image" />
            }
            else
            {
                <img src="~/css/ph3.jpg" class="profile-image" />
            }

            <form asp-action="UploadPhoto" asp-controller="UserAccount" method="post" enctype="multipart/form-data">
                <div class="file-input-wrapper">
                    <label for="file-upload" class="btn file-label">Выберите файл</label>
                    <input id="file-upload" type="file" name="photo" accept="image/*" required class="file-input" />
                    <input type="hidden" name="userId" value="@Model.UserId" />
                    <button type="submit" class="btn">Загрузить фотографию</button>
                </div>
            </form>
        </div>
            <div class="col-md-8">
                <h2>@Model.User.Username</h2>
                <label>@Model.Email</label>
                <br/>
                <label>@Model.Position</label>
                <br />
                <label>@Model.Phone</label>
            </div>

        </div>
</div>
</body>
</html>

MyDiplom/Views/UserAccount/DefaultView.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
   
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div>
        <h2>ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН</h2>
      
    </div>
</body>
</html>